version: "3.8"

services:
  mc1:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
      - "25576:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      RCON_PASSWORD: "pwd1"
      MAX_MEMORY: 2G
      RCON_PORT: 25575
      VERSION: "1.20.4"

  mc2:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25567:25565"
      - "25577:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      RCON_PASSWORD: "pwd2"
      MAX_MEMORY: 2G
      RCON_PORT: 25575
      VERSION: "1.18"

  css1:
    image: foxylion/steam-css
    ports:
      - "27016:27015"
    environment:
      RCON_PASSWORD: "pwd_css"

  pycon:
    build: .
    ports:
      - "8000:80"
    environment:
      DEFAULT_USER_PASSWORD: "test"
      LOG_LEVEL: "INFO"
