version: "3.8"

services:
  mc1:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      RCON_PASSWORD: "test_server_rcon_pwd"
      MAX_MEMORY: 2G
      RCON_PORT: 25575

  mc2:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
      - "25576:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      RCON_PASSWORD: "test_server_rcon_pwd2"
      MAX_MEMORY: 2G
      RCON_PORT: 25575
      